on:
  push:
    branches:
      - main

  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Check TypeScript definitions
        run: npm run check:schema:ts

      - name: Check draft-07 schema.json files are up to date
        run: npm run check:schema:json

      - name: Check 2020-12 schema.json files are up to date
        run: npm run check:schema:json:2020-12

      - name: Validate JSON Schema 2020-12 files
        run: npm run validate:schema:2020-12

      - name: Check schema.mdx files are up to date
        run: npm run check:schema:md
